// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TorresJ_Liga_Pro_de_Ecuador.Data;

#nullable disable

namespace TorresJ_Liga_Pro_de_Ecuador.Migrations
{
    [DbContext(typeof(TorresJ_Liga_Pro_de_EcuadorContext))]
    [Migration("20250430232252_AddEquipoTable")]
    partial class AddEquipoTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TorresJ_Liga_Pro_de_Ecuador.Models.Equipo", b =>
                {
                    b.Property<int>("IdEquipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEquipo"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreEquipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumPartidosEmpatados")
                        .HasColumnType("int");

                    b.Property<int>("NumPartidosGanados")
                        .HasColumnType("int");

                    b.Property<int>("NumPartidosJugados")
                        .HasColumnType("int");

                    b.Property<int>("NumPartidosPerdidos")
                        .HasColumnType("int");

                    b.Property<int>("Puntos")
                        .HasColumnType("int");

                    b.HasKey("IdEquipo");

                    b.ToTable("Equipo");
                });

            modelBuilder.Entity("TorresJ_Liga_Pro_de_Ecuador.Models.Jugador", b =>
                {
                    b.Property<string>("IdNombre")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdEquipoActual")
                        .HasColumnType("int");

                    b.Property<int>("asistencias")
                        .HasColumnType("int");

                    b.Property<int>("dorsal")
                        .HasColumnType("int");

                    b.Property<int>("goles")
                        .HasColumnType("int");

                    b.Property<decimal>("sueldo")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdNombre");

                    b.HasIndex("IdEquipoActual");

                    b.ToTable("Jugador");
                });

            modelBuilder.Entity("TorresJ_Liga_Pro_de_Ecuador.Models.Jugador", b =>
                {
                    b.HasOne("TorresJ_Liga_Pro_de_Ecuador.Models.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("IdEquipoActual")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });
#pragma warning restore 612, 618
        }
    }
}
